---
- hosts: all
  roles:
     - common
     - mariadb
     - nginx
     - letsencrypt   # adapted from https://gist.github.com/mattiaslundberg/ba214a35060d3c8603e9b1ec8627d349
     - nodejs
     - foodtrac