# adapted from https://gist.github.com/mattiaslundberg/ba214a35060d3c8603e9b1ec8627d349
---
- name: install python-simplejson
  apt: name=python-simplejson state=latest

- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: Install Nginx configuration for HTTP request redirect + Letsencrypt validation
  template:
    src: templates/foodtrac-http.jinja2
    dest: /etc/nginx/sites-available/foodtrac-http

- name: Enable Foodtrac Nginx configuration for HTTP request redirect + Letsencrypt validation
  file:
    src: /etc/nginx/sites-available/foodtrac-http
    dest: /etc/nginx/sites-enabled/foodtrac-http
    owner: root
    group: root
    state: link

- name: Reload nginx to perform letsencrypt validation
  service: name=nginx state=restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && systemctl nginx reload
