---
- name: install Foodtrac Nginx configuration
  tags: nginx
  notify:
  - reload nginx
  template:
    src: templates/foodtrac-https.jinja2
    dest: /etc/nginx/sites-available/foodtrac-https

- name: Enable Foodtrac Nginx configuration
  notify:
  - reload nginx
  file:
    src: /etc/nginx/sites-available/foodtrac-https
    dest: /etc/nginx/sites-enabled/foodtrac-https
    owner: root
    group: root
    state: link

