---
- name: create foodtrac system group
  group:
    name: foodtrac
    system: yes

- name: create foodtrac system user
  user:
    name: foodtrac
    group: foodtrac
    system: yes

- name: create foodtrac mysql/mariadb database
  mysql_db:
    name: foodtrac
    state: present
#    TODO: fix credential setup, should not be committing password to repo

- name: create foodtrac mysql/mariadb user
  mysql_user:
    name: foodtrac
    password: '12345'
    priv: 'foodtrac.*:ALL'
    state: present

- name: Install git package
  apt:
    state: latest
    name: git